/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package drawingwithmouse;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Point;
import javax.swing.JColorChooser;

/**
 *
 * @author Admin
 */
public class DrawWithMouse extends javax.swing.JFrame {

    Graphics g = null;
    Point p1 = null, p2 = null;
    Color color = Color.RED;

    public DrawWithMouse() {
        initComponents();
        g = this.pLines.getGraphics();
        this.rdFill.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btnColor = new javax.swing.JButton();
        rdDraw = new javax.swing.JRadioButton();
        rdFill = new javax.swing.JRadioButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pLines = new javax.swing.JPanel();
        pEllipses = new javax.swing.JPanel();
        pRectangles = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnColor.setText("Select Color");
        btnColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColorActionPerformed(evt);
            }
        });
        jPanel1.add(btnColor);

        buttonGroup1.add(rdDraw);
        rdDraw.setText("Draw Only");
        jPanel1.add(rdDraw);

        buttonGroup1.add(rdFill);
        rdFill.setText("Draw and Fill");
        jPanel1.add(rdFill);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        pLines.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pLinesMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pLinesMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout pLinesLayout = new javax.swing.GroupLayout(pLines);
        pLines.setLayout(pLinesLayout);
        pLinesLayout.setHorizontalGroup(
            pLinesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 395, Short.MAX_VALUE)
        );
        pLinesLayout.setVerticalGroup(
            pLinesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 239, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Lines", pLines);

        pEllipses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pEllipsesMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pEllipsesMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout pEllipsesLayout = new javax.swing.GroupLayout(pEllipses);
        pEllipses.setLayout(pEllipsesLayout);
        pEllipsesLayout.setHorizontalGroup(
            pEllipsesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 395, Short.MAX_VALUE)
        );
        pEllipsesLayout.setVerticalGroup(
            pEllipsesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 239, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Ellipses", pEllipses);

        pRectangles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pRectanglesMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pRectanglesMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout pRectanglesLayout = new javax.swing.GroupLayout(pRectangles);
        pRectangles.setLayout(pRectanglesLayout);
        pRectanglesLayout.setHorizontalGroup(
            pRectanglesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 395, Short.MAX_VALUE)
        );
        pRectanglesLayout.setVerticalGroup(
            pRectanglesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 239, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Rectangles", pRectangles);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColorActionPerformed
        color = JColorChooser.showDialog(this, "Choose a color", Color.BLACK);
        g.setColor(color);
    }//GEN-LAST:event_btnColorActionPerformed

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        int index = this.jTabbedPane1.getSelectedIndex();
        switch (index) {
            case 0:
                g = pLines.getGraphics();
                this.rdDraw.setSelected(true);
                this.rdFill.setSelected(false);
                break;
            case 1:
                g = pLines.getGraphics();
                this.rdFill.setSelected(true);
                break;
            case 2:
                g = pLines.getGraphics();
                this.rdFill.setSelected(true);
                break;
        }
        g.setColor(color);
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void pLinesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pLinesMousePressed
        p1 = evt.getPoint();
    }//GEN-LAST:event_pLinesMousePressed

    private void pLinesMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pLinesMouseReleased
        p2 = evt.getPoint();
        g.drawLine(p1.x, p1.y, p2.x, p2.y);
        p1 = p2 = null;
    }//GEN-LAST:event_pLinesMouseReleased

    private void pEllipsesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pEllipsesMousePressed
        p1 = evt.getPoint();
    }//GEN-LAST:event_pEllipsesMousePressed

    private void pEllipsesMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pEllipsesMouseReleased
        p2 = evt.getPoint();
        int left = p1.x < p2.x ? p1.x : p2.x;
        int top = p1.y < p2.y ? p1.y : p2.y;
        int width = p1.x - p2.x;
        if (width < 0) {
            width = -width;
        }
        int height = p1.y - p2.y;
        if (height < 0) {
            height = -height;
        }
        if (rdDraw.isSelected()) {
            g.drawOval(left, top, width, height);
        } else {
            g.fillOval(left, top, width, height);
        }
        p1 = p2 = null;
    }//GEN-LAST:event_pEllipsesMouseReleased

    private void pRectanglesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pRectanglesMousePressed
        p1 = evt.getPoint();
    }//GEN-LAST:event_pRectanglesMousePressed

    private void pRectanglesMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pRectanglesMouseReleased
        p2 = evt.getPoint();
        int left = p1.x < p2.x ? p1.x : p2.x;
        int top = p1.y < p2.y ? p1.y : p2.y;
        int width = p1.x - p2.x;
        if (width < 0) {
            width = -width;
        }
        int height = p1.y - p2.y;
        if (height < 0) {
            height = -height;
        }
        if (rdDraw.isSelected()) {
            g.drawRect(left, top, width, height);
        } else {
            g.fillRect(left, top, width, height);
        }
        p1 = p2 = null;
    }//GEN-LAST:event_pRectanglesMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DrawWithMouse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DrawWithMouse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DrawWithMouse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DrawWithMouse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DrawWithMouse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnColor;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel pEllipses;
    private javax.swing.JPanel pLines;
    private javax.swing.JPanel pRectangles;
    private javax.swing.JRadioButton rdDraw;
    private javax.swing.JRadioButton rdFill;
    // End of variables declaration//GEN-END:variables
}
