/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sp0116;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashSet;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class SP0116 extends javax.swing.JFrame {

    DefaultTableModel dftb;
    HashSet hs;
    public SP0116() {
        initComponents();
        dftb = new DefaultTableModel();
        hs = new HashSet();
        try {
            String sql ="use [FU_DB];\n"
                    +"SELECT * FROM dbo.Stocks";
            DBInfo dbContext = new DBInfo();
            Connection connection = dbContext.getConnection();
            Statement statement = connection.createStatement();
            statement.execute(sql);
            ResultSet rs = statement.getResultSet();
            Object[] title = {"StockID", "StockName", "Address", "DateAvailable", "Note"};
            dftb.setColumnIdentifiers(title);
            dftb.setRowCount(0);
            hs.clear();
            while (rs.next()) {
                Vector vector = new Vector();
                vector.add(rs.getString(1));
                hs.add(rs.getString(1));
                vector.add(rs.getString(2));
                vector.add(rs.getString(3));
                vector.add(rs.getString(4));
                vector.add(rs.getString(5));
                dftb.addRow(vector);
            }
            Table.setModel(dftb);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    public void insertData() throws Exception {
        DBInfo dbContext = new DBInfo();
        Connection connection = dbContext.getConnection();
        String sql = "use[FU_DB];\n"                
                + "BEGIN\n"
                + "Update dbo.Stocks\n"
                + "SET StockName='" + (String) Table.getValueAt(0, 1) + "',Address ='" +(String) Table.getValueAt(0, 2) + "',DateAvailable ='"+(String) Table.getValueAt(0, 3)+"',Note ='"+(String)Table.getValueAt(0, 4)+"'\n"
                + "Where StockID = "+Table.getValueAt(0, 0)+";"
                + "Update dbo.Stocks\n"
                + "SET StockName='" + (String) Table.getValueAt(1, 1) + "',Address ='" +(String) Table.getValueAt(1, 2) + "',DateAvailable ='"+(String) Table.getValueAt(1, 3)+"',Note ='"+(String)Table.getValueAt(1, 4)+"'\n"
                + "Where StockID = "+Table.getValueAt(1, 0)+";"
                + "Update dbo.Stocks\n"
                + "SET StockName='" + (String) Table.getValueAt(2, 1) + "',Address ='" +(String) Table.getValueAt(2, 2) + "',DateAvailable ='"+(String) Table.getValueAt(2, 3)+"',Note ='"+(String)Table.getValueAt(2, 4)+"'\n"
                + "Where StockID = "+Table.getValueAt(2, 0)+";"
                + "Update dbo.Stocks\n"
                + "SET StockName='" + (String) Table.getValueAt(3, 1) + "',Address ='" +(String) Table.getValueAt(3, 2) + "',DateAvailable ='"+(String) Table.getValueAt(3, 3)+"',Note ='"+(String)Table.getValueAt(3, 4)+"'\n"
                + "Where StockID = "+Table.getValueAt(3, 0)+";"
                + "Update dbo.Stocks\n"
                + "SET StockName='" + (String) Table.getValueAt(4, 1) + "',Address ='" +(String) Table.getValueAt(4, 2) + "',DateAvailable ='"+(String) Table.getValueAt(4, 3)+"',Note ='"+(String)Table.getValueAt(4, 4)+"'\n"
                + "Where StockID = "+Table.getValueAt(4, 0)+";"
                + "\n end";
        try {
            connection.setAutoCommit(false);
            Statement statement = connection.createStatement();
            statement.execute(sql);
            connection.commit();
            statement.close();     
            jLabel1.setText("Update success");
        } catch (SQLException e) {
            connection.rollback();
        }
        connection.close();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        Insert = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Table);

        Insert.setText("Insert to DB");
        Insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Insert, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Insert)
                    .addComponent(jLabel1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertActionPerformed
        try {
            insertData();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_InsertActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SP0116.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SP0116.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SP0116.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SP0116.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SP0116().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Insert;
    private javax.swing.JTable Table;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
